#!/bin/sh

CCRULES=/home/local/codecheck/rules
export CCRULES

echo Output will go to  stderr.out and check.lst

mv stderr.out stderr.out.old

check -D_POSIX_SOURCE \
-D__STDC__=1 -D__cplusplus=1 \
-L \
-O \
-K3 \
-A \
-Rposix \
-d__GNUG__ \
-d__wchar_t=int \
-I/usr/local/lib/gcc-lib/sparc-sun-sunos4.1.3/2.5.8/include \
-I/usr/include \
-I/home/local/X11R5/include -I/home/tools1/uimx2.5/motif12/usr/include \
fifotst.c \
fifo.c \
hash.c \
safe.c \
semops.c \
some_utils.c
