all:
	../montage -colors 256 -title "Image Montage" -geometry 160x160+10+10 \
	  -frame -borderwidth 15 -background \#103040 -foreground white \
	  -label "%f   %wx%h" -matte SlateGray -verbose dna.miff swan.miff \
	  aquarium.miff montage.miff

clean:
	/bin/rm -f montage.miff
